name: GovCMS CI Tests - PHPUnit

on:
  push:
    branches: [ "3.x-develop" ]
  pull_request:
    branches: [ "3.x-develop" ]

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      web:
        image: govcmstesting/ci:latest-php8.3-apache
        ports:
          - 80:80
        volumes:
          - .:/app/tests

    steps:
      - uses: actions/checkout@v4
      - name: Run PHPUnit tests
        run: |
           docker exec ${{ job.services.web.id }} govcms-phpunit --testdox --testsuite govcms-integration
  generate-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # specify the PHP version you need

      - name: Run PHP script to generate Markdown
        run: php phpunit/extract.php /home/runner/work/tests/tests/phpunit/integration/GovCMS

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add phpunit/docs/
          git commit -m "Update generated docs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
